import type { PublicCourseCard } from "@/features/catalog/catalogTypes";
import type { User } from "@/features/auth/authTypes";
export type EnrollmentStatus = "ACTIVE" | "COMPLETED" | "CANCELLED";
export type PaymentStatus = "NOT_REQUIRED" | "PENDING" | "PARTIAL" | "COMPLETED";
export type MyEnrollment = { enrolledAt: string; id: string; userId: string; courseId: string; status: EnrollmentStatus; paymentStatus: PaymentStatus; paymentCompletedAt?: string | null; completedAt?: string | null; createdAt: string; updatedAt: string; course: PublicCourseCard };
export type ClassRosterEntry = Omit<MyEnrollment, "course"> & { user: User };
export type CreateEnrollmentRequest = { userId: string; courseId: string; paymentStatus?: PaymentStatus };
export type UpdateEnrollmentRequest = { status?: EnrollmentStatus; paymentStatus?: PaymentStatus; paymentCompletedAt?: string | null; completedAt?: string | null };
export type EligibleStudent = Pick<User, "id" | "firstName" | "lastName" | "email">;
export type EligibleStudentsParams = { courseId: string; q?: string; limit?: number };
